/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type CreateRoleDto = {
  name: string;
  authority: number;
};

export type Role = {
  id: string;
  name: string;
  authority: number;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt: string | null;
};

export type ErrorDto = {
  message: string;
  error: string;
  statusCode: number;
};

export type SignUpDto = {
  handle: string;
  email: string;
  lastName: string;
  firstName: string;
  middleName: string;
  password: string;
};

export type SignInDto = {
  login: string;
  password: string;
};
